/**
 * Copy static site files and admin build output into a single `dist/` directory
 * for Vercel deployment.
 *
 * Static files: index.html, about.html, collections.html, contact.html, process.html,
 *               css/, js/, images/, content/
 * Admin build:  admin/dist/ → dist/admin/
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const DIST = path.join(ROOT, "dist");

// Ensure dist exists and is clean
fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

/**
 * Recursively copy `src` directory into `dest`.
 */
function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// Copy static HTML files
const htmlFiles = ["index.html", "about.html", "collections.html", "contact.html", "process.html"];
for (const file of htmlFiles) {
  const src = path.join(ROOT, file);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(DIST, file));
    console.log(`Copied ${file}`);
  }
}

// Copy static asset directories
const dirs = ["css", "js", "images", "content"];
for (const dir of dirs) {
  const src = path.join(ROOT, dir);
  if (fs.existsSync(src)) {
    copyDir(src, path.join(DIST, dir));
    console.log(`Copied ${dir}/`);
  }
}

// Generate dist/js/firebase-config.js from VITE_FIREBASE_* environment variables.
// This injects the same Firebase credentials used by the admin panel into the
// static storefront at build time, so overrides and hidden-product filtering work.
// If environment variables are not set (local dev), the placeholder file copied
// from js/ is kept as-is — fill in js/firebase-config.js directly for local dev.
{
  const requiredEnvVars = [
    "VITE_FIREBASE_API_KEY",
    "VITE_FIREBASE_AUTH_DOMAIN",
    "VITE_FIREBASE_PROJECT_ID",
    "VITE_FIREBASE_MESSAGING_SENDER_ID",
    "VITE_FIREBASE_APP_ID",
  ];
  const missing = requiredEnvVars.filter((k) => !process.env[k]);

  if (missing.length === 0) {
    const firebaseConfig = {
      apiKey: process.env.VITE_FIREBASE_API_KEY,
      authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN,
      projectId: process.env.VITE_FIREBASE_PROJECT_ID,
      storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET || "",
      messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: process.env.VITE_FIREBASE_APP_ID,
    };
    const configContent =
      "/**\n" +
      " * Firebase configuration for the static storefront.\n" +
      " * Auto-generated at build time from VITE_FIREBASE_* environment variables.\n" +
      " * Do not edit this file manually — edit js/firebase-config.js for local dev.\n" +
      " */\n" +
      "window.FIREBASE_CONFIG = " +
      JSON.stringify(firebaseConfig, null, 2) +
      ";\n";
    fs.writeFileSync(path.join(DIST, "js", "firebase-config.js"), configContent);
    console.log("Generated js/firebase-config.js from VITE_FIREBASE_* environment variables");
  } else if (missing.length < requiredEnvVars.length) {
    // Some (but not all) vars are set — warn and keep the placeholder to avoid a broken config.
    console.warn(
      "Warning: Some VITE_FIREBASE_* variables are missing: " +
        missing.join(", ") +
        ".\n" +
        "         Keeping placeholder js/firebase-config.js to avoid a partial config.\n" +
        "         Set all required variables for Firebase to work on the storefront."
    );
  } else {
    console.log(
      "Note: VITE_FIREBASE_* environment variables not set — keeping placeholder js/firebase-config.js.\n" +
        "      Set all VITE_FIREBASE_* variables for production builds."
    );
  }
}

// Copy admin build output to dist/admin/
const adminDist = path.join(ROOT, "admin", "dist");
if (fs.existsSync(adminDist)) {
  copyDir(adminDist, path.join(DIST, "admin"));
  console.log("Copied admin/dist/ → dist/admin/");
} else {
  console.warn("Warning: admin/dist/ not found. Run npm run build:admin first.");
}

console.log("Build complete → dist/");
